### ISSUE TITLE
connection issue: Invalid token?

### ISSUE THREAD

**Issue by ghost** [Johni0702/mumble-web-proxy#18]
I always try to set mumble-web-proxy up but it always returns this error: ClientConnection(Io(Custom { kind: Other, error: "invalid token" })) on a new connection. I couldnt really find out what that means and what that token is.

**Comment by Simon-Boyer** [comment]
I had the same problem, but once I added HTTPS certificates to the mumble-web and the mumble-web-proxy it worked. Seems like since it uses wss you have to have certificates set up. Even when you disable every security check on chrome it still fails without valid certificates from trusted sources.

**Comment by ghost** [comment]
@Simon-Boyer And where do I set the certificate to mumble-web and mumble-web-proxy?

**Comment by Johni0702** [comment]
[As it says in the README](https://github.com/Johni0702/mumble-web-proxy#running), mumble-web-proxy cannot accept TLS connections and you need to run a webserver which is capable of handling TLS in front of it.

**Comment by ghost** [comment]
The webserver I run(on which mumble-web runs) uses TLS - so I dont know where the problem is.

**Comment by Johni0702** [comment]
It must also handle mumble-web-proxy connections and remove the TLS from those before passing them on to mumble-web-proxy. E.g. for Nginx the `location /demo` block: https://github.com/Johni0702/mumble-web#setup
