### ISSUE TITLE
Process user disconnect

### ISSUE THREAD

**Issue by UndeRus** [Johni0702/mumble-web-proxy#26]
I don't get any events when user disconnects:
- MediaStream.onremovetrack not called
- MediaStreamTrack.onmute not called too

**Comment by Johni0702** [comment]
That's correct.
User disconnects are signaled only via Mumble's regular `UserRemove` message.
The MediaStreamTracks are left as they are and will be re-used for future users, see [here](https://github.com/Johni0702/rust-mumble-protocol/blob/50c0fd35c3934734c51a22ce662dca412d1667d7/protos/MumbleWithWebRTC.proto#L221-L226).

**Comment by UndeRus** [comment]
thank you very much, it helped a lot
