### ISSUE TITLE
mumble-web-proxy fails to run when server has ipv6 disabled?

### ISSUE THREAD

**Issue by surfrock66** [Johni0702/mumble-web-proxy#32]
I had mumble-web-proxy working, but for another service I had to disable ipv6.  Now when I run mumble-web-proxy, I get the following output:

`Error: Io(Os { code: 97, kind: Other, message: "Address family not supported by protocol" })`

I recompiled just in case this was something impacted at build time, and it didn't change anything.

**Comment by surfrock66** [comment]
So I don't know rust, but if I open up main.js and change line 181 from this:

`    let socket_addr = (Ipv6Addr::from(0), ws_port);`

to this:

`    let socket_addr = (Ipv4Addr::from(0), ws_port);`

It works on ipv4.  It seems the better solution is to check if ipv6 is working, THEN fall back to ipv4 on failure so that socket_addr gets populated first by v6 then v4, but I'm not familiar enough with rust to do that properly.  For now, my local branch is working.

**Comment by Skgland** [comment]
@surfrock66 did you have a change to see if #33 has solved your problem?

**Comment by surfrock66** [comment]
I hadn't seen that, I'll try it out when I get a chance today and report back, thanks!

**Comment by surfrock66** [comment]
As far as I can tell it's good to go, thanks!
