### ISSUE TITLE
mumble-web-proxy: command not found

### ISSUE THREAD

**Issue by reza3320** [Johni0702/mumble-web-proxy#35]
I built the app successfully nut the command not works!

```root@server:/home/pi/mumble-web-proxy/target/release# mumble-web-proxy --help
bash: mumble-web-proxy: command not found```

**Comment by JuniorJPDJ** [comment]
what was the problem? please show us solution if you are closing issue

**Comment by reza3320** [comment]
> what was the problem? please show us solution if you are closing issue

I made a pull request and I upgraded the read me about it.
This error appears when you are not in the right directory
(https://github.com/reza3320/mumble-web-proxy/commit/2b0f45a576b4a409b023dc1e0070b377abb9bf35)
