### ISSUE TITLE
crash with "Illegal instruction"

### ISSUE THREAD

**Issue by streaps** [Johni0702/mumble-web-proxy#7]
mumble-web-proxy crashed on first webrtc connection. 

```
New connection from [::1]:37144
MSG Authenticate: username: "asdasdasd" password: "" opus: false webrtc: true
Local ice candidate: 1 1 UDP 2013266431 fe80::116:3eff:fe89:525c 30893 typ host
Local ice candidate: 2 1 TCP 1015022847 fe80::116:3eff:fe89:525c 0 typ host tcptype active
Local ice candidate: 3 1 TCP 1010828543 fe80::116:3eff:fe89:525c 30009 typ host tcptype passive
Local ice candidate: 4 1 UDP 2013266430 10.3.3.16 30347 typ host
Local ice candidate: 5 1 TCP 1015022079 10.3.3.16 0 typ host tcptype active
Local ice candidate: 6 1 TCP 1010827775 10.3.3.16 30096 typ host tcptype passive
Got WebRTC: ice_pwd: "4O8O+a7Cz3Dx8LyugavQUdUZ" ice_ufrag: "971X" dtls_fingerprint: "58:53:64:C3:5F:E3:77:CD:82:49:9F:19:2E:6F:8B:3D:6E:25:EC:9C:32:37:94:E5:6B:3D:20:F0:89:DF:BC:AD"
Got ice candidate: "candidate:854070991 1 udp 2122260223 192.168.1.11 60363 typ host generation 0 ufrag 971X network-id 1"
Got ice candidate: "candidate:2558760555 1 udp 2122194687 10.20.0.2 59813 typ host generation 0 ufrag 971X network-id 2"
Got ice candidate: "candidate:2087447103 1 tcp 1518280447 192.168.1.11 9 typ host tcptype active generation 0 ufrag 971X network-id 1"
Got ice candidate: "candidate:3590351515 1 tcp 1518214911 10.20.0.2 9 typ host tcptype active generation 0 ufrag 971X network-id 2"
DTLS-SRTP connection established.
Illegal instruction
```

**Comment by Johni0702** [comment]
Could you `cargo build` (i.e. without `--release`) and then run it via gdb to get a backtrace?
```
cargo build
gdb target/debug/mumble-web-proxy
run --listen-ws 64737 --server mumbleserver:64738
```
it should then run as usual and when it crashes, it should prompt you again and `bt` will print a backtrace.
If it doesn't crash without `--release`, then just run the non-debug version via gdb. I'm just not sure if the `bt` will be as useful.

Given the error is "Illegal instruction", which machine is this running on (specifically, OS and CPU)?
Have you compiled it on the same machine as it's running on? (if you haven't, then the machine running it might just legitimately not support one of the instructions)
Which libnice version are you using?

**Comment by streaps** [comment]
Same machine (lxc container), but it is Alpine Linux with musl.
libnice is 0.1.16

I will try building/running it in Debian and gdb.

**Comment by streaps** [comment]
zipped bt:
[gdb_bt.zip](https://github.com/Johni0702/mumble-web-proxy/files/4580605/gdb_bt.zip)

**Comment by streaps** [comment]
I think it is a problem with rust-crypto and missing avx support on the VPS I'm using.

**Comment by Johni0702** [comment]
Looks like `rust-crypto` relies on the CPU supporting the [AVX](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions) instructions and yours presumably doesn't: https://github.com/DaGenix/rust-crypto/issues/390

`rust-crypto` seems dead, so looking at how other projects dealt with this, I'm going to do the same as decided in https://github.com/librespot-org/librespot/issues/128 and push that in a minute or so.

**Comment by Johni0702** [comment]
Above commit should work around the problem.
Please give it a try and if it works, close this issue.

**Comment by streaps** [comment]
very good :)
